name = str(input("what is your name ? "))
age = int(input("what is your age ? "))
course_code = str(input("what is your course code ?  "))
print (name)
print(age)
print(course_code)
print(type(name))
print(type(age))
print(type(course_code))